name: Build Dev

on:
  push:
    branches: [develop]
    paths:
      - jupyterhub/**
      - share/**
      - jsx/**
      - bower-lite
      - package.json
      - package-lock.json
      - pyproject.toml
      - setup.py
      - MANIFEST.in
      - requirements.txt
      - Dockerfile
      - .github/workflows/build-dev.yml

permissions:
  id-token: write
  contents: write

jobs:
  build:
    uses: team-monolith-product/tmn-gh-actions/.github/workflows/build_v2.yml@main
    with:
      env: dev
      target: develop
      dockerTarget: tmn-stateless-hub
      helmRepository: enk-opencode-hub-helm
      propertyPath: jupyterhub.hub.image.tag
      updateTargets: |
        {
          "aws": {
            "imageName": "tmn-ecr-stateless-hub-all-dev",
            "valueFilePath": ["aws-apne2-dev-hackathon.yaml"]
          }
        }
    secrets:
      MACHINE_TOKEN: ${{ secrets.MACHINE_TOKEN }}
