name: Build Dev

on:
  push:
    branches: [develop]

permissions:
  id-token: write
  contents: write

jobs:
  build:
    uses: team-monolith-product/tmn-gh-actions/.github/workflows/build_v2.yml@main
    with:
      env: dev
      target: develop
      dockerTarget: tmn-stateless-hub-dev
      helmRepository: enk-opencode-hub-helm
      propertyPath: jupyterhub.hub.image.tag
      updateTargets: |
        {
          "aws": {
            "imageName": "tmn-ecr-stateless-hub-all-dev",
            "valueFilePath": ["aws-apne2-dev-hackathon.yaml"]
          }
        }
    secrets:
      MACHINE_TOKEN: ${{ secrets.MACHINE_TOKEN }}
