name: Upload Package Prd

on:
  push:
    branches: [main]

jobs:
  upload:
    uses: ./.github/workflows/upload-package.yml
    with:
      env: prd
      repository_url: https://nexus.codle.io/repository/pypi-internal/
      dockerfile_branch: main
    secrets:
      AUTOMATION_APP_PRIVATE_KEY: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
      NEXUS_PYPI_MACHINE_PASSWORD: ${{ secrets.NEXUS_PYPI_MACHINE_PASSWORD }}
